(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var l="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ba(this);function q(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&l(c,a,{configurable:!0,writable:!0,value:b})}}
q("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(g||"")+"_"+e++,g)}function c(g,f){this.g=g;l(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
q("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&l(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});q("Symbol.asyncIterator",function(a){return a?a:Symbol("Symbol.asyncIterator")});
function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}function r(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var da;
if("function"==typeof Object.setPrototypeOf)da=Object.setPrototypeOf;else{var ea;a:{var fa={a:!0},ha={};try{ha.__proto__=fa;ea=ha.a;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var t=da;function ia(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
q("Promise",function(a){function b(f){this.g=0;this.i=void 0;this.h=[];this.u=!1;var h=this.j();try{f(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(f){return f instanceof b?f:new b(function(h){h(f)})}if(a)return a;c.prototype.h=function(f){if(null==this.g){this.g=[];var h=this;this.i(function(){h.l()})}this.g.push(f)};var e=p.setTimeout;c.prototype.i=function(f){e(f,0)};c.prototype.l=function(){for(;this.g&&this.g.length;){var f=this.g;this.g=[];for(var h=0;h<f.length;++h){var k=
f[h];f[h]=null;try{k()}catch(m){this.j(m)}}}this.g=null};c.prototype.j=function(f){this.i(function(){throw f;})};b.prototype.j=function(){function f(m){return function(n){k||(k=!0,m.call(h,n))}}var h=this,k=!1;return{resolve:f(this.D),reject:f(this.l)}};b.prototype.D=function(f){if(f===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.T(f);else{a:switch(typeof f){case "object":var h=null!=f;break a;case "function":h=!0;break a;default:h=!1}h?this.C(f):this.o(f)}};
b.prototype.C=function(f){var h=void 0;try{h=f.then}catch(k){this.l(k);return}"function"==typeof h?this.U(h,f):this.o(f)};b.prototype.l=function(f){this.v(2,f)};b.prototype.o=function(f){this.v(1,f)};b.prototype.v=function(f,h){if(0!=this.g)throw Error("Cannot settle("+f+", "+h+"): Promise already settled in state"+this.g);this.g=f;this.i=h;2===this.g&&this.G();this.A()};b.prototype.G=function(){var f=this;e(function(){if(f.B()){var h=p.console;"undefined"!==typeof h&&h.error(f.i)}},1)};b.prototype.B=
function(){if(this.u)return!1;var f=p.CustomEvent,h=p.Event,k=p.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof h?f=new h("unhandledrejection",{cancelable:!0}):(f=p.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.i;return k(f)};b.prototype.A=function(){if(null!=this.h){for(var f=0;f<this.h.length;++f)g.h(this.h[f]);this.h=null}};var g=new c;b.prototype.T=
function(f){var h=this.j();f.F(h.resolve,h.reject)};b.prototype.U=function(f,h){var k=this.j();try{f.call(h,k.resolve,k.reject)}catch(m){k.reject(m)}};b.prototype.then=function(f,h){function k(y,G){return"function"==typeof y?function(ka){try{m(y(ka))}catch(la){n(la)}}:G}var m,n,v=new b(function(y,G){m=y;n=G});this.F(k(f,m),k(h,n));return v};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.F=function(f,h){function k(){switch(m.g){case 1:f(m.i);break;case 2:h(m.i);break;default:throw Error("Unexpected state: "+
m.g);}}var m=this;null==this.h?g.h(k):this.h.push(k);this.u=!0};b.resolve=d;b.reject=function(f){return new b(function(h,k){k(f)})};b.race=function(f){return new b(function(h,k){for(var m=r(f),n=m.next();!n.done;n=m.next())d(n.value).F(h,k)})};b.all=function(f){var h=r(f),k=h.next();return k.done?d([]):new b(function(m,n){function v(ka){return function(la){y[ka]=la;G--;0==G&&m(y)}}var y=[],G=0;do y.push(void 0),G++,d(k.value).F(v(y.length-1),n),k=h.next();while(!k.done)})};return b});
function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
q("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=r(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(k){var m=typeof k;return"object"===m&&null!==k||"function"===m}function e(k){if(!u(k,f)){var m=new c;l(k,f,{value:m})}}function g(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),
n=new a([[k,2],[m,3]]);if(2!=n.get(k)||3!=n.get(m))return!1;n.delete(k);n.set(m,4);return!n.has(k)&&4==n.get(m)}catch(v){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();g("freeze");g("preventExtensions");g("seal");var h=0;b.prototype.set=function(k,m){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,f))throw Error("WeakMap key fail: "+k);k[f][this.g]=m;return this};b.prototype.get=function(k){return d(k)&&u(k,f)?k[f][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
f)&&u(k[f],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,f)&&u(k[f],this.g)?delete k[f][this.g]:!1};return b});
q("Map",function(a){function b(){var h={};return h.s=h.next=h.head=h}function c(h,k){var m=h.g;return ca(function(){if(m){for(;m.head!=h.g;)m=m.s;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})}function d(h,k){var m=k&&typeof k;"object"==m||"function"==m?g.has(k)?m=g.get(k):(m=""+ ++f,g.set(k,m)):m="p_"+k;var n=h.h[m];if(n&&u(h.h,m))for(h=0;h<n.length;h++){var v=n[h];if(k!==k&&v.key!==v.key||k===v.key)return{id:m,list:n,index:h,m:v}}return{id:m,list:n,
index:-1,m:void 0}}function e(h){this.h={};this.g=b();this.size=0;if(h){h=r(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(r([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=h||"s"!=n.value[1])return!1;n=m.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!m.next().done?!1:!0}catch(v){return!1}}())return a;var g=new WeakMap;e.prototype.set=function(h,k){h=0===h?0:h;var m=d(this,h);m.list||(m.list=this.h[m.id]=[]);m.m?m.m.value=k:(m.m={next:this.g,s:this.g.s,head:this.g,key:h,value:k},m.list.push(m.m),this.g.s.next=m.m,this.g.s=m.m,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.m&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.h[h.id],h.m.s.next=h.m.next,h.m.next.s=h.m.s,h.m.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.h={};this.g=this.g.s=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).m};e.prototype.get=function(h){return(h=d(this,h).m)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,
h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});function ja(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var g=a[e];if(b.call(c,g,e,a))return{K:e,S:g}}return{K:-1,S:void 0}}q("Array.prototype.find",function(a){return a?a:function(b,c){return ja(this,b,c).S}});
function w(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}q("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=w(this,b,"endsWith");void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}});
q("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=w(this,b,"startsWith"),e=d.length,g=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var f=0;f<g&&c<e;)if(d[c++]!=b[f++])return!1;return f>=g}});q("Number.isFinite",function(a){return a?a:function(b){return"number"!==typeof b?!1:!isNaN(b)&&Infinity!==b&&-Infinity!==b}});
q("String.prototype.repeat",function(a){return a?a:function(b){var c=w(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}});q("String.prototype.trimLeft",function(a){function b(){return this.replace(/^[\s\xa0]+/,"")}return a||b});q("String.prototype.trimStart",function(a){return a||String.prototype.trimLeft});q("Object.setPrototypeOf",function(a){return a||t});
var ma="function"==typeof Object.assign?Object.assign:function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};q("Object.assign",function(a){return a||ma});q("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||Infinity===b||-Infinity===b||0===b)return b;var c=Math.floor(Math.abs(b));return 0>b?-c:c}});function na(a){a=Math.trunc(a)||0;0>a&&(a+=this.length);if(!(0>a||a>=this.length))return this[a]}
q("Array.prototype.at",function(a){return a?a:na});
q("Array.prototype.copyWithin",function(a){function b(c){c=Number(c);return Infinity===c||-Infinity===c?c:c|0}return a?a:function(c,d,e){var g=this.length;c=b(c);d=b(d);e=void 0===e?g:b(e);c=0>c?Math.max(g+c,0):Math.min(c,g);d=0>d?Math.max(g+d,0):Math.min(d,g);e=0>e?Math.max(g+e,0):Math.min(e,g);if(c<d)for(;d<e;)d in this?this[c++]=this[d++]:(delete this[c++],d++);else for(e=Math.min(e,g+d-c),c+=e-d;e>d;)--e in this?this[--c]=this[e]:delete this[--c];return this}});
function oa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}q("Array.prototype.entries",function(a){return a?a:function(){return oa(this,function(b,c){return[b,c]})}});
q("Array.prototype.fill",function(a){return a?a:function(b,c,d){var e=this.length||0;0>c&&(c=Math.max(0,e+c));if(null==d||d>e)d=e;d=Number(d);0>d&&(d=Math.max(0,e+d));for(c=Number(c||0);c<d;c++)this[c]=b;return this}});q("Array.prototype.findIndex",function(a){return a?a:function(b,c){return ja(this,b,c).K}});
q("Array.prototype.flat",function(a){return a?a:function(b){b=void 0===b?1:b;var c=[];Array.prototype.forEach.call(this,function(d){Array.isArray(d)&&0<b?(d=Array.prototype.flat.call(d,b-1),c.push.apply(c,d)):c.push(d)});return c}});q("Array.prototype.flatMap",function(a){return a?a:function(b,c){var d=[];Array.prototype.forEach.call(this,function(e,g){e=b.call(c,e,g,this);Array.isArray(e)?d.push.apply(d,e):d.push(e)});return d}});
q("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],g="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof g){b=g.call(b);for(var f=0;!(g=b.next()).done;)e.push(c.call(d,g.value,f++))}else for(g=b.length,f=0;f<g;f++)e.push(c.call(d,b[f],f));return e}});q("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
q("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var g=d[c];if(g===b||Object.is(g,b))return!0}return!1}});q("Array.prototype.keys",function(a){return a?a:function(){return oa(this,function(b){return b})}});q("Array.of",function(a){return a?a:function(b){return Array.from(arguments)}});q("Array.prototype.values",function(a){return a?a:function(){return oa(this,function(b,c){return c})}});
q("globalThis",function(a){return a||p});q("Math.acosh",function(a){return a?a:function(b){b=Number(b);return Math.log(b+Math.sqrt(b*b-1))}});q("Math.asinh",function(a){return a?a:function(b){b=Number(b);if(0===b)return b;var c=Math.log(Math.abs(b)+Math.sqrt(b*b+1));return 0>b?-c:c}});q("Math.log1p",function(a){return a?a:function(b){b=Number(b);if(.25>b&&-.25<b){for(var c=b,d=1,e=b,g=0,f=1;g!=e;)c*=b,f*=-1,e=(g=e)+f*c/++d;return e}return Math.log(1+b)}});
q("Math.atanh",function(a){if(a)return a;var b=Math.log1p;return function(c){c=Number(c);return(b(c)-b(-c))/2}});q("Math.cbrt",function(a){return a?a:function(b){if(0===b)return b;b=Number(b);var c=Math.pow(Math.abs(b),1/3);return 0>b?-c:c}});q("Math.clz32",function(a){return a?a:function(b){b=Number(b)>>>0;if(0===b)return 32;var c=0;0===(b&4294901760)&&(b<<=16,c+=16);0===(b&4278190080)&&(b<<=8,c+=8);0===(b&4026531840)&&(b<<=4,c+=4);0===(b&3221225472)&&(b<<=2,c+=2);0===(b&2147483648)&&c++;return c}});
q("Math.cosh",function(a){if(a)return a;var b=Math.exp;return function(c){c=Number(c);return(b(c)+b(-c))/2}});q("Math.expm1",function(a){return a?a:function(b){b=Number(b);if(.25>b&&-.25<b){for(var c=b,d=1,e=b,g=0;g!=e;)c*=b/++d,e=(g=e)+c;return e}return Math.exp(b)-1}});q("Math.fround",function(a){if(a)return a;if("function"!==typeof Float32Array)return function(c){return c};var b=new Float32Array(1);return function(c){b[0]=c;return b[0]}});
q("Math.hypot",function(a){return a?a:function(b){if(2>arguments.length)return arguments.length?Math.abs(arguments[0]):0;var c,d,e;for(c=e=0;c<arguments.length;c++)e=Math.max(e,Math.abs(arguments[c]));if(1E100<e||1E-100>e){if(!e)return e;for(c=d=0;c<arguments.length;c++){var g=Number(arguments[c])/e;d+=g*g}return Math.sqrt(d)*e}for(c=d=0;c<arguments.length;c++)g=Number(arguments[c]),d+=g*g;return Math.sqrt(d)}});
q("Math.imul",function(a){return a?a:function(b,c){b=Number(b);c=Number(c);var d=b&65535,e=c&65535;return d*e+((b>>>16&65535)*e+d*(c>>>16&65535)<<16>>>0)|0}});q("Math.log10",function(a){return a?a:function(b){return Math.log(b)/Math.LN10}});q("Math.log2",function(a){return a?a:function(b){return Math.log(b)/Math.LN2}});q("Math.sign",function(a){return a?a:function(b){b=Number(b);return 0===b||isNaN(b)?b:0<b?1:-1}});
q("Math.sinh",function(a){if(a)return a;var b=Math.exp;return function(c){c=Number(c);return 0===c?c:(b(c)-b(-c))/2}});q("Math.tanh",function(a){return a?a:function(b){b=Number(b);if(0===b)return b;var c=Math.exp(-2*Math.abs(b));c=(1-c)/(1+c);return 0>b?-c:c}});q("Number.EPSILON",function(){return Math.pow(2,-52)});q("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});q("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});
q("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});q("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});q("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});q("Number.parseFloat",function(a){return a||parseFloat});q("Number.parseInt",function(a){return a||parseInt});
q("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});q("Object.fromEntries",function(a){return a?a:function(b){var c={};if(!(Symbol.iterator in b))throw new TypeError(""+b+" is not iterable");b=b[Symbol.iterator].call(b);for(var d=b.next();!d.done;d=b.next()){d=d.value;if(Object(d)!==d)throw new TypeError("iterable for fromEntries should yield objects");c[d[0]]=d[1]}return c}});q("Reflect",function(a){return a?a:{}});
q("Object.getOwnPropertySymbols",function(a){return a?a:function(){return[]}});q("Reflect.ownKeys",function(a){return a?a:function(b){var c=[],d=Object.getOwnPropertyNames(b);b=Object.getOwnPropertySymbols(b);for(var e=0;e<d.length;e++)("jscomp_symbol_"==d[e].substring(0,14)?b:c).push(d[e]);return c.concat(b)}});q("Object.getOwnPropertyDescriptors",function(a){return a?a:function(b){for(var c={},d=Reflect.ownKeys(b),e=0;e<d.length;e++)c[d[e]]=Object.getOwnPropertyDescriptor(b,d[e]);return c}});
q("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push(b[d]);return c}});q("Object.hasOwn",function(a){return a?a:function(b,c){return Object.prototype.hasOwnProperty.call(b,c)}});q("Promise.allSettled",function(a){function b(d){return{status:"fulfilled",value:d}}function c(d){return{status:"rejected",reason:d}}return a?a:function(d){var e=this;d=Array.from(d,function(g){return e.resolve(g).then(b,c)});return e.all(d)}});
q("Promise.prototype.finally",function(a){return a?a:function(b){return this.then(function(c){return Promise.resolve(b()).then(function(){return c})},function(c){return Promise.resolve(b()).then(function(){throw c;})})}});var pa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};
function qa(a,b){a.prototype=pa(b.prototype);a.prototype.constructor=a;if(t)t(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.V=b.prototype}q("AggregateError",function(a){function b(c,d){d=Error(d);"stack"in d&&(this.stack=d.stack);this.errors=c;this.message=d.message}if(a)return a;qa(b,Error);b.prototype.name="AggregateError";return b});
q("Promise.any",function(a){return a?a:function(b){b=b instanceof Array?b:Array.from(b);return Promise.all(b.map(function(c){return Promise.resolve(c).then(function(d){throw d;},function(d){return d})})).then(function(c){throw new AggregateError(c,"All promises were rejected");},function(c){return c})}});q("Reflect.apply",function(a){if(a)return a;var b=Function.prototype.apply;return function(c,d,e){return b.call(c,d,e)}});
var ra=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=pa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();q("Reflect.construct",function(){return ra});
q("Reflect.defineProperty",function(a){return a?a:function(b,c,d){try{Object.defineProperty(b,c,d);var e=Object.getOwnPropertyDescriptor(b,c);return e?e.configurable===(d.configurable||!1)&&e.enumerable===(d.enumerable||!1)&&("value"in e?e.value===d.value&&e.writable===(d.writable||!1):e.get===d.get&&e.set===d.set):!1}catch(g){return!1}}});q("Reflect.deleteProperty",function(a){return a?a:function(b,c){if(!u(b,c))return!0;try{return delete b[c]}catch(d){return!1}}});
q("Reflect.getOwnPropertyDescriptor",function(a){return a||Object.getOwnPropertyDescriptor});q("Reflect.getPrototypeOf",function(a){return a||Object.getPrototypeOf});function sa(a,b){for(;a;){var c=Reflect.getOwnPropertyDescriptor(a,b);if(c)return c;a=Reflect.getPrototypeOf(a)}}q("Reflect.get",function(a){return a?a:function(b,c,d){if(2>=arguments.length)return b[c];var e=sa(b,c);if(e)return e.get?e.get.call(d):e.value}});q("Reflect.has",function(a){return a?a:function(b,c){return c in b}});
q("Reflect.isExtensible",function(a){return a?a:"function"==typeof Object.isExtensible?Object.isExtensible:function(){return!0}});q("Reflect.preventExtensions",function(a){return a?a:"function"!=typeof Object.preventExtensions?function(){return!1}:function(b){Object.preventExtensions(b);return!Object.isExtensible(b)}});
q("Reflect.set",function(a){return a?a:function(b,c,d,e){var g=sa(b,c);return g?g.set?(g.set.call(3<arguments.length?e:b,d),!0):g.writable&&!Object.isFrozen(b)?(b[c]=d,!0):!1:Reflect.isExtensible(b)?(b[c]=d,!0):!1}});q("Reflect.setPrototypeOf",function(a){return a?a:t?function(b,c){try{return t(b,c),!0}catch(d){return!1}}:null});
q("Set",function(a){function b(c){this.g=new Map;if(c){c=r(c);for(var d;!(d=c.next()).done;)this.add(d.value)}this.size=this.g.size}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),d=new a(r([c]));if(!d.has(c)||1!=d.size||d.add(c)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),g=e.next();if(g.done||g.value[0]!=c||g.value[1]!=c)return!1;g=e.next();return g.done||g.value[0]==c||4!=g.value[0].x||
g.value[1]!=g.value[0]?!1:e.next().done}catch(f){return!1}}())return a;b.prototype.add=function(c){c=0===c?0:c;this.g.set(c,c);this.size=this.g.size;return this};b.prototype.delete=function(c){c=this.g.delete(c);this.size=this.g.size;return c};b.prototype.clear=function(){this.g.clear();this.size=0};b.prototype.has=function(c){return this.g.has(c)};b.prototype.entries=function(){return this.g.entries()};b.prototype.values=function(){return this.g.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(c,d){var e=this;this.g.forEach(function(g){return c.call(d,g,g,e)})};return b});q("String.prototype.at",function(a){return a?a:na});q("String.prototype.codePointAt",function(a){return a?a:function(b){var c=w(this,null,"codePointAt"),d=c.length;b=Number(b)||0;if(0<=b&&b<d){b|=0;var e=c.charCodeAt(b);if(55296>e||56319<e||b+1===d)return e;b=c.charCodeAt(b+1);return 56320>b||57343<b?e:1024*(e-55296)+b+9216}}});
q("String.fromCodePoint",function(a){return a?a:function(b){for(var c="",d=0;d<arguments.length;d++){var e=Number(arguments[d]);if(0>e||1114111<e||e!==Math.floor(e))throw new RangeError("invalid_code_point "+e);65535>=e?c+=String.fromCharCode(e):(e-=65536,c+=String.fromCharCode(e>>>10&1023|55296),c+=String.fromCharCode(e&1023|56320))}return c}});q("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==w(this,b,"includes").indexOf(b,c||0)}});
q("String.prototype.matchAll",function(a){return a?a:function(b){if(b instanceof RegExp&&!b.global)throw new TypeError("RegExp passed into String.prototype.matchAll() must have global tag.");var c=new RegExp(b,b instanceof RegExp?void 0:"g"),d=this,e=!1,g={next:function(){if(e)return{value:void 0,done:!0};var f=c.exec(d);if(!f)return e=!0,{value:void 0,done:!0};""===f[0]&&(c.lastIndex+=1);return{value:f,done:!1}}};g[Symbol.iterator]=function(){return g};return g}});
function ta(a,b){a=void 0!==a?String(a):" ";return 0<b&&a?a.repeat(Math.ceil(b/a.length)).substring(0,b):""}q("String.prototype.padEnd",function(a){return a?a:function(b,c){var d=w(this,null,"padStart");return d+ta(c,b-d.length)}});q("String.prototype.padStart",function(a){return a?a:function(b,c){var d=w(this,null,"padStart");return ta(c,b-d.length)+d}});
q("String.raw",function(a){return a?a:function(b,c){if(null==b)throw new TypeError("Cannot convert undefined or null to object");for(var d=b.raw,e=d.length,g="",f=0;f<e;++f)g+=d[f],f+1<e&&f+1<arguments.length&&(g+=String(arguments[f+1]));return g}});
q("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});q("String.prototype.trimRight",function(a){function b(){return this.replace(/[\s\xa0]+$/,"")}return a||b});
q("String.prototype.trimEnd",function(a){return a||String.prototype.trimRight});function x(a){return a?a:na}q("Int8Array.prototype.at",x);q("Uint8Array.prototype.at",x);q("Uint8ClampedArray.prototype.at",x);q("Int16Array.prototype.at",x);q("Uint16Array.prototype.at",x);q("Int32Array.prototype.at",x);q("Uint32Array.prototype.at",x);q("Float32Array.prototype.at",x);q("Float64Array.prototype.at",x);function z(a){return a?a:Array.prototype.copyWithin}q("Int8Array.prototype.copyWithin",z);
q("Uint8Array.prototype.copyWithin",z);q("Uint8ClampedArray.prototype.copyWithin",z);q("Int16Array.prototype.copyWithin",z);q("Uint16Array.prototype.copyWithin",z);q("Int32Array.prototype.copyWithin",z);q("Uint32Array.prototype.copyWithin",z);q("Float32Array.prototype.copyWithin",z);q("Float64Array.prototype.copyWithin",z);function A(a){return a?a:Array.prototype.fill}q("Int8Array.prototype.fill",A);q("Uint8Array.prototype.fill",A);q("Uint8ClampedArray.prototype.fill",A);
q("Int16Array.prototype.fill",A);q("Uint16Array.prototype.fill",A);q("Int32Array.prototype.fill",A);q("Uint32Array.prototype.fill",A);q("Float32Array.prototype.fill",A);q("Float64Array.prototype.fill",A);
q("WeakSet",function(a){function b(c){this.g=new WeakMap;if(c){c=r(c);for(var d;!(d=c.next()).done;)this.add(d.value)}}if(function(){if(!a||!Object.seal)return!1;try{var c=Object.seal({}),d=Object.seal({}),e=new a([c]);if(!e.has(c)||e.has(d))return!1;e.delete(c);e.add(d);return!e.has(c)&&e.has(d)}catch(g){return!1}}())return a;b.prototype.add=function(c){this.g.set(c,!0);return this};b.prototype.has=function(c){return this.g.has(c)};b.prototype.delete=function(c){return this.g.delete(c)};return b});
var B=this||self;function ua(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function va(a,b,c){return a.call.apply(a.bind,arguments)}function wa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function C(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?C=va:C=wa;return C.apply(null,arguments)}function D(a,b){a=a.split(".");var c=B;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}
function E(a,b){function c(){}c.prototype=b.prototype;a.V=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.W=function(d,e,g){for(var f=Array(arguments.length-2),h=2;h<arguments.length;h++)f[h-2]=arguments[h];return b.prototype[e].apply(d,f)}}function xa(a){return a};function F(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,F);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));void 0!==b&&(this.cause=b)}E(F,Error);F.prototype.name="CustomError";function H(a,b){this.g=a===ya&&b||"";this.h=za}H.prototype.L=!0;H.prototype.J=function(){return this.g};function Aa(a){return a instanceof H&&a.constructor===H&&a.h===za?a.g:"type_error:Const"}function I(a){return new H(ya,a)}var za={},ya={};var Ba={"gstatic.com":{loader:I("https://www.gstatic.com/charts/%{version}/loader.js"),debug:I("https://www.gstatic.com/charts/debug/%{version}/js/jsapi_debug_%{package}_module.js"),debug_i18n:I("https://www.gstatic.com/charts/debug/%{version}/i18n/jsapi_debug_i18n_%{package}_module__%{language}.js"),compiled:I("https://www.gstatic.com/charts/%{version}/js/jsapi_compiled_%{package}_module.js"),compiled_i18n:I("https://www.gstatic.com/charts/%{version}/i18n/jsapi_compiled_i18n_%{package}_module__%{language}.js"),
css:I("https://www.gstatic.com/charts/%{version}/css/%{subdir}/%{filename}"),css2:I("https://www.gstatic.com/charts/%{version}/css/%{subdir1}/%{subdir2}/%{filename}"),third_party:I("https://www.gstatic.com/charts/%{version}/third_party/%{subdir}/%{filename}"),third_party2:I("https://www.gstatic.com/charts/%{version}/third_party/%{subdir1}/%{subdir2}/%{filename}"),third_party_gen:I("https://www.gstatic.com/charts/%{version}/third_party/%{subdir}/%{filename}")},"gstatic.cn":{loader:I("https://www.gstatic.cn/charts/%{version}/loader.js"),
debug:I("https://www.gstatic.cn/charts/debug/%{version}/js/jsapi_debug_%{package}_module.js"),debug_i18n:I("https://www.gstatic.cn/charts/debug/%{version}/i18n/jsapi_debug_i18n_%{package}_module__%{language}.js"),compiled:I("https://www.gstatic.cn/charts/%{version}/js/jsapi_compiled_%{package}_module.js"),compiled_i18n:I("https://www.gstatic.cn/charts/%{version}/i18n/jsapi_compiled_i18n_%{package}_module__%{language}.js"),css:I("https://www.gstatic.cn/charts/%{version}/css/%{subdir}/%{filename}"),
css2:I("https://www.gstatic.cn/charts/%{version}/css/%{subdir1}/%{subdir2}/%{filename}"),third_party:I("https://www.gstatic.cn/charts/%{version}/third_party/%{subdir}/%{filename}"),third_party2:I("https://www.gstatic.cn/charts/%{version}/third_party/%{subdir1}/%{subdir2}/%{filename}"),third_party_gen:I("https://www.gstatic.cn/charts/%{version}/third_party/%{subdir}/%{filename}")}},Ca=["default"],Da={"default":[],graphics:["default"],ui:["graphics"],ui_base:["graphics"],flashui:["ui"],fw:["ui"],geo:["ui"],
annotatedtimeline:["annotationchart"],annotationchart:["ui","controls","corechart","table"],areachart:"browserchart",bar:["fw","webfontloader"],barchart:"browserchart",browserchart:["ui"],bubbles:["fw","d3"],calendar:["fw"],charteditor:"ui corechart imagechart annotatedtimeline gauge geochart motionchart orgchart table".split(" "),charteditor_base:"ui_base corechart imagechart annotatedtimeline gauge geochart motionchart orgchart table_base".split(" "),circles:["fw","d3"],clusterchart:["corechart",
"d3"],columnchart:"browserchart",controls:["ui"],controls_base:["ui_base"],corechart:["ui"],gantt:["fw"],gauge:["ui"],geochart:["geo"],geomap:["flashui","geo"],geomap_base:["ui_base"],helloworld:["fw"],imagechart:["ui"],imageareachart:"imagechart",imagebarchart:"imagechart",imagelinechart:"imagechart",imagepiechart:"imagechart",imagesparkline:"imagechart",line:["fw","webfontloader"],linechart:"browserchart",map:["geo"],matrix:["vegachart"],motionchart:["flashui"],orgchart:["ui"],overtimecharts:["ui",
"corechart"],piechart:"browserchart",sankey:["fw","d3","d3.sankey"],scatter:["fw","webfontloader"],scatterchart:"browserchart",sunburst:["fw","d3"],streamgraph:["fw","d3"],table:["ui"],table_base:["ui_base"],timeline:["fw","ui"],treemap:["ui"],vegachart:["graphics"],wordtree:["ui"]},Ea={d3:{subdir1:"d3",subdir2:"v5",filename:"d3.js"},"d3.sankey":{subdir1:"d3_sankey",subdir2:"v4",filename:"d3.sankey.js"},webfontloader:{subdir:"webfontloader",filename:"webfont.js"}},Fa={},Ga={"default":[{subdir:"core",
filename:"tooltip.css"}],annotationchart:[{subdir:"annotationchart",filename:"annotationchart.css"}],charteditor:[{subdir:"charteditor",filename:"charteditor.css"}],charteditor_base:[{subdir:"charteditor_base",filename:"charteditor_base.css"}],controls:[{subdir:"controls",filename:"controls.css"}],imagesparkline:[{subdir:"imagechart",filename:"imagesparkline.css"}],orgchart:[{subdir:"orgchart",filename:"orgchart.css"}],table:[{subdir:"table",filename:"table.css"},{subdir:"util",filename:"format.css"}],
table_base:[{subdir:"util",filename:"format.css"},{subdir:"table",filename:"table_base.css"}],ui:[{subdir:"util",filename:"util.css"}],ui_base:[{subdir:"util",filename:"util_base.css"}]};var Ha=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};function Ia(a,b){a:{for(var c="string"===typeof a?a.split(""):a,d=a.length-1;0<=d;d--)if(d in c&&b.call(void 0,c[d],d,a)){b=d;break a}b=-1}return 0>b?null:"string"===typeof a?a.charAt(b):a[b]}
function Ja(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];var e=typeof d;e="object"!=e?e:d?Array.isArray(d)?"array":e:"null";if("array"==e||"object"==e&&"number"==typeof d.length){e=a.length||0;var g=d.length||0;a.length=e+g;for(var f=0;f<g;f++)a[e+f]=d[f]}else a.push(d)}};function Ka(){};var J;function K(a,b){this.g=b===La?a:""}K.prototype.toString=function(){return this.g+""};K.prototype.L=!0;K.prototype.J=function(){return this.g.toString()};function L(a){return a instanceof K&&a.constructor===K?a.g:"type_error:TrustedResourceUrl"}
function Ma(a,b){var c=Aa(a);if(!Na.test(c))throw Error("Invalid TrustedResourceUrl format: "+c);a=c.replace(Oa,function(d,e){if(!Object.prototype.hasOwnProperty.call(b,e))throw Error('Found marker, "'+e+'", in format string, "'+c+'", but no valid label mapping found in args: '+JSON.stringify(b));d=b[e];return d instanceof H?Aa(d):encodeURIComponent(String(d))});return Pa(a)}
var Oa=/%{(\w+)}/g,Na=RegExp("^((https:)?//[0-9a-z.:[\\]-]+/|/[^/\\\\]|[^:/\\\\%]+/|[^:/\\\\%]*[?#]|about:blank#)","i"),Qa=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,La={};function Pa(a){if(void 0===J){var b=null;var c=B.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:xa,createScript:xa,createScriptURL:xa})}catch(d){B.console&&B.console.error(d.message)}J=b}else J=b}a=(b=J)?b.createScriptURL(a):a;return new K(a,La)}
function Ra(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?e:[e];for(var g=0;g<e.length;g++){var f=e[g];null!=f&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(f)))}}return b};var Sa,M;a:{for(var Ta=["CLOSURE_FLAGS"],N=B,Ua=0;Ua<Ta.length;Ua++)if(N=N[Ta[Ua]],null==N){M=null;break a}M=N}var Va=M&&M[610401301];Sa=null!=Va?Va:!1;var Wa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};function Xa(a,b){return a<b?-1:a>b?1:0};function O(){var a=B.navigator;return a&&(a=a.userAgent)?a:""}var Ya,Za=B.navigator;Ya=Za?Za.userAgentData||null:null;function P(a){return-1!=O().indexOf(a)};function $a(){return Sa?!!Ya&&0<Ya.brands.length:!1}function ab(){return $a()?!1:P("Trident")||P("MSIE")};/*

 Copyright 2021 Google LLC
 This code is released under the MIT license.
 SPDX-License-Identifier: MIT
*/
function bb(a){var b=cb;return Object.prototype.hasOwnProperty.call(b,11)?b[11]:b[11]=a(11)};var db=$a()?!1:P("Opera"),eb=ab(),fb=P("Edge"),gb=P("Gecko")&&!(-1!=O().toLowerCase().indexOf("webkit")&&!P("Edge"))&&!(P("Trident")||P("MSIE"))&&!P("Edge"),hb=-1!=O().toLowerCase().indexOf("webkit")&&!P("Edge"),ib;
a:{var jb="",kb=function(){var a=O();if(gb)return/rv:([^\);]+)(\)|;)/.exec(a);if(fb)return/Edge\/([\d\.]+)/.exec(a);if(eb)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(hb)return/WebKit\/(\S+)/.exec(a);if(db)return/(?:Version)[ \/]?(\S+)/.exec(a)}();kb&&(jb=kb?kb[1]:"");if(eb){var lb,mb=B.document;lb=mb?mb.documentMode:void 0;if(null!=lb&&lb>parseFloat(jb)){ib=String(lb);break a}}ib=jb}var nb=ib,cb={};
function ob(){return bb(function(){for(var a=0,b=Wa(String(nb)).split("."),c=Wa("11").split("."),d=Math.max(b.length,c.length),e=0;0==a&&e<d;e++){var g=b[e]||"",f=c[e]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];if(0==g[0].length&&0==f[0].length)break;a=Xa(0==g[1].length?0:parseInt(g[1],10),0==f[1].length?0:parseInt(f[1],10))||Xa(0==g[2].length,0==f[2].length)||Xa(g[2],f[2]);g=g[3];f=f[3]}while(0==a)}return 0<=a})};function pb(a,b){for(var c in a)b.call(void 0,a[c],c,a)}var qb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function rb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var g=0;g<qb.length;g++)c=qb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function sb(a,b){a:{var c=(a.ownerDocument&&a.ownerDocument.defaultView||B).document;if(c.querySelector&&(c=c.querySelector("script[nonce]"))&&(c=c.nonce||c.getAttribute("nonce"))&&tb.test(c))break a;c=""}c&&a.setAttribute("nonce",c);a.src=L(b)}var tb=/^[\w+/_-]+[=]{0,2}$/;function ub(a,b){pb(b,function(c,d){c&&"object"==typeof c&&c.L&&(c=c.J());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:vb.hasOwnProperty(d)?a.setAttribute(vb[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var vb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function wb(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)}function xb(a){this.g=a||B.document||document};function yb(){};function zb(a,b){this.i=a;this.j=b;this.h=0;this.g=null}zb.prototype.get=function(){if(0<this.h){this.h--;var a=this.g;this.g=a.next;a.next=null}else a=this.i();return a};function Ab(a,b){a.j(b);100>a.h&&(a.h++,b.next=a.g,a.g=b)};var Bb;
function Cb(){var a=B.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!P("Presto")&&(a=function(){var e=wb(document,"IFRAME");e.style.display="none";document.documentElement.appendChild(e);var g=e.contentWindow;e=g.document;e.open();e.close();var f="callImmediate"+Math.random(),h="file:"==g.location.protocol?"*":g.location.protocol+"//"+g.location.host;e=C(function(k){if(("*"==h||k.origin==h)&&k.data==f)this.port1.onmessage()},this);
g.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){g.postMessage(f,h)}}});if("undefined"!==typeof a&&!ab()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.I;c.I=null;e()}};return function(e){d.next={I:e};d=d.next;b.port2.postMessage(0)}}return function(e){B.setTimeout(e,0)}};function Db(a){B.setTimeout(function(){throw a;},0)};function Eb(){this.h=this.g=null}Eb.prototype.add=function(a,b){var c=Fb.get();c.set(a,b);this.h?this.h.next=c:this.g=c;this.h=c};function Gb(){var a=Hb,b=null;a.g&&(b=a.g,a.g=a.g.next,a.g||(a.h=null),b.next=null);return b}var Fb=new zb(function(){return new Ib},function(a){return a.reset()});function Ib(){this.next=this.g=this.h=null}Ib.prototype.set=function(a,b){this.h=a;this.g=b;this.next=null};Ib.prototype.reset=function(){this.next=this.g=this.h=null};var Jb,Kb=!1,Hb=new Eb;function Lb(a,b){Jb||Mb();Kb||(Jb(),Kb=!0);Hb.add(a,b)}function Mb(){if(B.Promise&&B.Promise.resolve){var a=B.Promise.resolve(void 0);Jb=function(){a.then(Nb)}}else Jb=function(){var b=Nb;"function"!==typeof B.setImmediate||B.Window&&B.Window.prototype&&($a()||!P("Edge"))&&B.Window.prototype.setImmediate==B.setImmediate?(Bb||(Bb=Cb()),Bb(b)):B.setImmediate(b)}}function Nb(){for(var a;a=Gb();){try{a.h.call(a.g)}catch(b){Db(b)}Ab(Fb,a)}Kb=!1};function Ob(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function Q(a){this.g=0;this.u=void 0;this.j=this.h=this.i=null;this.l=this.o=!1;if(a!=Ka)try{var b=this;a.call(void 0,function(c){R(b,2,c)},function(c){R(b,3,c)})}catch(c){R(this,3,c)}}function Pb(){this.next=this.i=this.h=this.j=this.g=null;this.l=!1}Pb.prototype.reset=function(){this.i=this.h=this.j=this.g=null;this.l=!1};var Qb=new zb(function(){return new Pb},function(a){a.reset()});function Rb(a,b,c){var d=Qb.get();d.j=a;d.h=b;d.i=c;return d}
Q.prototype.then=function(a,b,c){return Sb(this,"function"===typeof a?a:null,"function"===typeof b?b:null,c)};Q.prototype.$goog_Thenable=!0;Q.prototype.cancel=function(a){if(0==this.g){var b=new S(a);Lb(function(){Tb(this,b)},this)}};function Tb(a,b){if(0==a.g)if(a.i){var c=a.i;if(c.h){for(var d=0,e=null,g=null,f=c.h;f&&(f.l||(d++,f.g==a&&(e=f),!(e&&1<d)));f=f.next)e||(g=f);e&&(0==c.g&&1==d?Tb(c,b):(g?(d=g,d.next==c.j&&(c.j=d),d.next=d.next.next):Ub(c),Vb(c,e,3,b)))}a.i=null}else R(a,3,b)}
function Wb(a,b){a.h||2!=a.g&&3!=a.g||Xb(a);a.j?a.j.next=b:a.h=b;a.j=b}function Sb(a,b,c,d){var e=Rb(null,null,null);e.g=new Q(function(g,f){e.j=b?function(h){try{var k=b.call(d,h);g(k)}catch(m){f(m)}}:g;e.h=c?function(h){try{var k=c.call(d,h);void 0===k&&h instanceof S?f(h):g(k)}catch(m){f(m)}}:f});e.g.i=a;Wb(a,e);return e.g}Q.prototype.A=function(a){this.g=0;R(this,2,a)};Q.prototype.B=function(a){this.g=0;R(this,3,a)};
function R(a,b,c){if(0==a.g){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.g=1;a:{var d=c,e=a.A,g=a.B;if(d instanceof Q){Wb(d,Rb(e||Ka,g||null,a));var f=!0}else if(Ob(d))d.then(e,g,a),f=!0;else{if(ua(d))try{var h=d.then;if("function"===typeof h){Yb(d,h,e,g,a);f=!0;break a}}catch(k){g.call(a,k);f=!0;break a}f=!1}}f||(a.u=c,a.g=b,a.i=null,Xb(a),3!=b||c instanceof S||Zb(a,c))}}
function Yb(a,b,c,d,e){function g(k){h||(h=!0,d.call(e,k))}function f(k){h||(h=!0,c.call(e,k))}var h=!1;try{b.call(a,f,g)}catch(k){g(k)}}function Xb(a){a.o||(a.o=!0,Lb(a.v,a))}function Ub(a){var b=null;a.h&&(b=a.h,a.h=b.next,b.next=null);a.h||(a.j=null);return b}Q.prototype.v=function(){for(var a;a=Ub(this);)Vb(this,a,this.g,this.u);this.o=!1};
function Vb(a,b,c,d){if(3==c&&b.h&&!b.l)for(;a&&a.l;a=a.i)a.l=!1;if(b.g)b.g.i=null,$b(b,c,d);else try{b.l?b.j.call(b.i):$b(b,c,d)}catch(e){ac.call(null,e)}Ab(Qb,b)}function $b(a,b,c){2==b?a.j.call(a.i,c):a.h&&a.h.call(a.i,c)}function Zb(a,b){a.l=!0;Lb(function(){a.l&&ac.call(null,b)})}var ac=Db;function S(a){F.call(this,a)}E(S,F);S.prototype.name="cancel";/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
function T(a,b){this.l=[];this.D=a;this.C=b||null;this.j=this.i=!1;this.h=void 0;this.A=this.G=this.u=!1;this.o=0;this.g=null;this.v=0}E(T,yb);T.prototype.cancel=function(a){if(this.i)this.h instanceof T&&this.h.cancel();else{if(this.g){var b=this.g;delete this.g;a?b.cancel(a):(b.v--,0>=b.v&&b.cancel())}this.D?this.D.call(this.C,this):this.A=!0;this.i||(a=new U(this),V(this),W(this,!1,a))}};T.prototype.B=function(a,b){this.u=!1;W(this,a,b)};function W(a,b,c){a.i=!0;a.h=c;a.j=!b;bc(a)}
function V(a){if(a.i){if(!a.A)throw new cc(a);a.A=!1}}function dc(a,b,c,d){a.l.push([b,c,d]);a.i&&bc(a)}T.prototype.then=function(a,b,c){var d,e,g=new Q(function(f,h){e=f;d=h});dc(this,e,function(f){f instanceof U?g.cancel():d(f);return ec},this);return g.then(a,b,c)};T.prototype.$goog_Thenable=!0;function fc(a){return Ha(a.l,function(b){return"function"===typeof b[1]})}var ec={};
function bc(a){if(a.o&&a.i&&fc(a)){var b=a.o,c=gc[b];c&&(B.clearTimeout(c.g),delete gc[b]);a.o=0}a.g&&(a.g.v--,delete a.g);b=a.h;for(var d=c=!1;a.l.length&&!a.u;){var e=a.l.shift(),g=e[0],f=e[1];e=e[2];if(g=a.j?f:g)try{var h=g.call(e||a.C,b);h===ec&&(h=void 0);void 0!==h&&(a.j=a.j&&(h==b||h instanceof Error),a.h=b=h);if(Ob(b)||"function"===typeof B.Promise&&b instanceof B.Promise)d=!0,a.u=!0}catch(k){b=k,a.j=!0,fc(a)||(c=!0)}}a.h=b;d&&(h=C(a.B,a,!0),d=C(a.B,a,!1),b instanceof T?(dc(b,h,d),b.G=!0):
b.then(h,d));c&&(b=new hc(b),gc[b.g]=b,a.o=b.g)}function ic(){var a=new T;V(a);W(a,!0,null);return a}function cc(){F.call(this)}E(cc,F);cc.prototype.message="Deferred has already fired";cc.prototype.name="AlreadyCalledError";function U(){F.call(this)}E(U,F);U.prototype.message="Deferred was canceled";U.prototype.name="CanceledError";function hc(a){this.g=B.setTimeout(C(this.i,this),0);this.h=a}hc.prototype.i=function(){delete gc[this.g];throw this.h;};var gc={};var jc,kc=[];function lc(a,b){function c(){var e=a.shift();e=mc(e,b);a.length&&dc(e,c,c);return e}if(!a.length)return ic();var d=kc.length;Ja(kc,a);if(d)return jc;a=kc;return jc=c()}
function mc(a,b){var c=b||{};b=c.document||document;var d=L(a).toString(),e=wb((new xb(b)).g,"SCRIPT"),g={O:e,P:void 0},f=new T(nc,g),h=null,k=null!=c.timeout?c.timeout:5E3;0<k&&(h=window.setTimeout(function(){oc(e,!0);var m=new pc(1,"Timeout reached for loading script "+d);V(f);W(f,!1,m)},k),g.P=h);e.onload=e.onreadystatechange=function(){e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(oc(e,c.X||!1,h),V(f),W(f,!0,null))};e.onerror=function(){oc(e,!0,h);var m=new pc(0,"Error while loading script "+
d);V(f);W(f,!1,m)};g=c.attributes||{};rb(g,{type:"text/javascript",charset:"UTF-8"});ub(e,g);sb(e,a);qc(b).appendChild(e);return f}function qc(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&0!==b.length?b[0]:a.documentElement}function nc(){if(this&&this.O){var a=this.O;a&&"SCRIPT"==a.tagName&&oc(a,!0,this.P)}}
function oc(a,b,c){null!=c&&B.clearTimeout(c);a.onload=function(){};a.onerror=function(){};a.onreadystatechange=function(){};b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}function pc(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);F.call(this,c);this.code=a}E(pc,F);function rc(a){var b=a.M||{};a=Ma(a.format,a.H);a=Qa.exec(L(a).toString());var c=a[3]||"";return Pa(a[1]+Ra("?",a[2]||"",b)+Ra("#",c))}var sc=mc;function tc(a){var b=a.map(rc);if(0===b.length)return Promise.resolve();a={timeout:3E4,attributes:{async:!1,defer:!1}};var c=[];if(!eb||ob()){b=r(b);for(var d=b.next();!d.done;d=b.next())c.push(sc(d.value,a))}else c.push(lc(b,a));return Promise.all(c.map(function(e){return new Promise(function(g){dc(e,g,null)})}))};/*

 Copyright 2021 Google LLC
 This code is released under the MIT license.
 SPDX-License-Identifier: MIT

*/
function uc(){return new Promise(function(a){"undefined"===typeof window||"complete"===document.readyState?a():window.addEventListener?(document.addEventListener("DOMContentLoaded",a,!0),window.addEventListener("load",a,!0)):window.attachEvent?window.attachEvent("onload",a):"function"!==typeof window.onload?window.onload=a:window.onload=function(b){if(window.onload)window.onload(b);a()}})}var X={};function vc(a){X[a]||(X[a]={loaded:!1});X[a].loaded=!0};var wc=0;
function xc(a,b){b=b||document;var c="load-css-"+wc++,d=b.createElement("link");d.setAttribute("id",c);d.setAttribute("rel","stylesheet");d.setAttribute("type","text/css");return new Promise(function(e,g){void 0!==d.addEventListener?(d.addEventListener("load",e,!1),d.addEventListener("error",g,!1)):void 0!==d.attachEvent&&d.attachEvent("onload",function(){try{Ia(b.styleSheets,function(f){return f.id===c})&&(vc(a),e())}catch(f){g()}});try{(b.querySelector("head")||b).appendChild(d),d.setAttribute("href",a)}catch(f){e()}})}
function yc(a,b){return Promise.all(a.map(function(c){c=rc(c);return xc(L(c).toString(),b)}))};var Y="",zc="",Ac=!1,Bc=!1,Z;function Cc(a){function b(d){for(var e=[],g=0;g<d.length;g++){var f=d[g];if(!c[f]){c[f]=!0;var h=Da[f]||[];e=e.concat(b("string"===typeof h?[h]:h));"string"!==typeof h&&e.push(f)}}return e}var c={};return b(a)}function Dc(a){var b=[],c=[];a.forEach(function(d){var e=X[d]&&X[d].promise;void 0!==e?b.push(e):c.push(d)});return{N:b,R:c}}
function Ec(a){a=Dc(Cc(a));var b=a.N,c=a.R,d=c.map(function(g){var f={version:Y,language:zc,"package":g};Ea[g]?(g=Ea[g],Object.assign(f,g),g=Z[g.subdir?"third_party":"third_party2"]):Fa[g]?(Object.assign(f,Fa[g]),g=Z.third_party_gen):g=Z[(Ac?"debug":Bc?"pseudo":"compiled")+(zc?"_i18n":"")];return g?{format:g,H:f,M:void 0}:null}).filter(function(g){return null!=g}),e=Promise.all(b).then(function(){return tc(d)}).then(function(){c.forEach(function(g){vc(g)})});c.forEach(function(g){X[g]={promise:e,
loaded:!1}});return e}
function Fc(a,b){a=Cc(a);var c=[];a.forEach(function(k){(Ga[k]||[]).forEach(function(m){c.push(m)})});if(0===c.length)return Promise.resolve();var d={};a=c.map(function(k){var m=(k.subdir||k.subdir1+"/"+k.subdir2)+"/"+k.filename;d[m]=k;return m});a=Dc(a);var e=a.N,g=a.R,f=g.map(function(k){k=d[k];var m=Z.css,n={version:Y,subdir:k.subdir,filename:k.filename};k.subdir2&&(m=Z.css2,n.subdir1=k.subdir1,n.subdir2=k.subdir2);return{format:m,H:n,M:void 0}}),h=Promise.all(e).then(function(){return yc(f,b)}).then(function(){g.forEach(function(k){vc(k)})});
g.forEach(function(k){X[k]={promise:h,loaded:!1}});return h}function Gc(a,b){D("goog.visualization.isSafeMode",b.safeMode||!1);var c=b.debug||!1,d=b.pseudo||!1,e=b.language||"";zc=e;a||(a=b.version||"unknown");a=a||"";""!==Y&&Y!==a&&(a=Y);a=Y=a||"";Ac=c;Bc=d;D("google.visualization.ModulePath",Z.format);D("google.visualization.Version",a);D("google.visualization.Locale",e);D("google.visualization.isDebug",c);D("google.visualization.isPseudo",d);D("google.visualization.mapsApiKey",b.mapsApiKey)}
var Hc=null;function Ic(a,b){function c(e){return e.getRootNode?e.getRootNode():null!=e.parentNode?c(e.parentNode):e}Gc(a,b);a=b.packages;Array.isArray(a)&&0!==a.length||(a=Ca);var d=c(b.element||document);return Hc=Promise.all([Fc(a,d),Ec(a),b.ignoreWindowOnLoad?Promise.resolve():uc()]).then(function(){var e=b.callback;if(e){if("function"!==typeof e)throw Error("Callback must be a function");e()}})}
D("google.charts.loader.versionSpecific.load",function(){var a=ia.apply(0,arguments),b=0;"visualization"===a[b]&&b++;var c="current";"string"===typeof a[b]&&(c=a[b],b++);var d={};ua(a[b])&&(d=a[b]);Z||(Z=Ba[d.domain||"gstatic.com"]);return Ic(c,d)});D("google.charts.loader.versionSpecific.setOnLoadCallback",function(a){if(!Hc)throw Error("Must call google.charts.load before google.charts.setOnLoadCallback");if(!a)return Hc;if("function"!==typeof a)throw Error("Callback must be a function");return Hc.then(a)});}).call(this);
